#!/usr/bin/env bash
set -euo pipefail
. "$(dirname "$0")/lib.sh"

MAN="$TEMPLATE_DIR/.just/manifests"
OUT="$DOCS_DIR/assets/project-data.js"
mkdir -p "$DOCS_DIR/assets"

info "Building $OUT from the real tree + manifests"

emit()   { printf '%s'   "$*" >> "$OUT"; }
emitln() { printf '%s\n' "$*" >> "$OUT"; }

: > "$OUT"
emitln "// Generated by scripts/docs-build.sh — do not edit by hand."
emitln "// Regenerate with: just docs-build"
emitln "window.PROJECT_DATA = {"

# --- tree ------------------------------------------------------------------
emitln '  "tree": ['
first=1
while IFS= read -r p; do
    [ "$p" = "$TEMPLATE_DIR" ] && continue
    rel="${p#"$TEMPLATE_DIR"/}"
    if [ -d "$p" ]; then type="dir"; else type="file"; fi
    depth=$(awk -F/ '{print NF-1}' <<< "$rel")
    [ "$first" -eq 1 ] || emitln ","
    first=0
    emit "    {\"path\": $(json_str "$rel"), \"type\": \"$type\", \"depth\": $depth}"
done < <(find "$TEMPLATE_DIR" -not -path '*/.git/*' | LC_ALL=C sort)
emitln ""
emitln "  ],"

# --- commands --------------------------------------------------------------
emitln '  "commands": ['
first=1
while IFS=$'\t' read -r c cat mod plats desc; do
    [ "$first" -eq 1 ] || emitln ","
    first=0
    emit "    {\"command\": $(json_str "$c"), \"category\": $(json_str "$cat"), \"module\": $(json_str "$mod"), \"platforms\": $(json_str "$plats"), \"description\": $(json_str "$desc")}"
done < <(tsv_rows "$MAN/commands.tsv")
emitln ""
emitln "  ],"

# --- tools -----------------------------------------------------------------
emitln '  "tools": ['
first=1
while IFS=$'\t' read -r c arch deb mac win req plats desc; do
    [ "$first" -eq 1 ] || emitln ","
    first=0
    emit "    {\"command\": $(json_str "$c"), \"arch\": $(json_str "$arch"), \"debian\": $(json_str "$deb"), \"macos\": $(json_str "$mac"), \"windows\": $(json_str "$win"), \"required\": $(json_str "$req"), \"platforms\": $(json_str "$plats"), \"description\": $(json_str "$desc")}"
done < <(tsv_rows "$MAN/tools.tsv")
emitln ""
emitln "  ],"

# --- platforms -------------------------------------------------------------
emitln '  "platforms": ['
first=1
while IFS=$'\t' read -r id detect mgr install adapter; do
    [ "$first" -eq 1 ] || emitln ","
    first=0
    emit "    {\"id\": $(json_str "$id"), \"detect\": $(json_str "$detect"), \"manager\": $(json_str "$mgr"), \"install\": $(json_str "$install"), \"adapter\": $(json_str "$adapter")}"
done < <(tsv_rows "$MAN/platforms.tsv")
emitln ""
emitln "  ],"

# --- env -------------------------------------------------------------------
emitln '  "env": ['
first=1
while read -r v; do
    [ -n "$v" ] || continue
    [ "$first" -eq 1 ] || emitln ","
    first=0
    emit "    $(json_str "$v")"
done < <(grep -vE '^[[:space:]]*(#|$)' "$MAN/env.required" | sed -E 's/[[:space:]]//g')
emitln ""
emitln "  ],"

# --- rules (architecture invariants) ---------------------------------------
rules=(
    "Modules define WHAT to do; adapters define HOW. OS logic never lives in a module."
    "OS-sensitive recipes use the [unix] and [windows] attributes, not the deprecated windows-shell setting."
    "Every module sets its own shell and working-directory, so it runs standalone and namespaced (just db backup == just db::backup)."
    "Manifests (TSV) are the single source of truth: scripts and this dashboard read them; nothing is duplicated by hand."
    "Optional modules use mod? and can be deleted without breaking the rest of the configuration."
    "Platform columns and rows are always ordered Arch, Debian, macOS, Windows."
    "Adding an OS = one platforms.tsv row + one tools.tsv column + one adapter file. No module changes."
)
emitln '  "rules": ['
first=1
for r in "${rules[@]}"; do
    [ "$first" -eq 1 ] || emitln ","
    first=0
    emit "    $(json_str "$r")"
done
emitln ""
emitln "  ]"
emitln "};"

ok "Wrote $OUT"
